api = "0.2"

[buildpack]
  id = "oscarnevarezleal/simple-packit-buildpack"
  name = "Demo"
  version = "0.0.1"

[[stacks]]
  id = "io.paketo.stacks.tiny"
[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  [[metadata.dependencies]]
    uri = "https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz"
